spring:
  application:
    name: gateway-server
  # zipkin:
  #   baseUrl: http://${ZIPKIN:localhost}:9411
  # sleuth:
  #   sampler:
  #     percentage: 1
  cloud:
    gateway:
      discovery:
        # this enable eureka path
        # locator:
        #   enabled: true
        #   lower-case-service-id: true

        - route_id: ReactiveCompositeDiscoveryClient_PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}
        
        # - id: team-service
        #   uri: lb://TEAM-SERVICE
        #   predicates:
        #     - Path=/teamapi/**
        #   filters:
        #     - RewritePath=/teamapi/(?<path>.*), /$\{path}

    loadbalancer.ribbon.enabled: false

server:
  port: 7072

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKASERVER:localhost}:7070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
