spring:
  application:
    name: gateway-server
  # zipkin:
  #   baseUrl: http://${ZIPKIN:localhost}:9411
  # sleuth:
  #   sampler:
  #     percentage: 1
  cloud:
    gateway:
      discovery:
        # this enable eureka path
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
          - Path=/api/v1/product/**
          filters:
          - RewritePath=/api/v1/product/(?<path>.*), /$\{path}
        # - id: openapi
        #   uri: http://localhost:${server.port}
        #   predicates:
        #   - Path=/v3/api-docs/**
        #   filters:
        #   - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

    # loadbalancer.ribbon.enabled: false

# springdoc:
#   swagger-ui:
#     urls:
#       - name: product
#         url: /v3/api-docs/product


server:
  port: 7072

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKASERVER:localhost}:7070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
